import type { Metadata } from "next";
import MUIThemeProvider from "@/providers/ThemeProvider";
import CacheProvider from "@/providers/CacheProvider";
import NotiStackProvider from "@/providers/NotiStackProvider";
import Footer from "@/components/Footer";
import TopLoader from "@/providers/TopLoader";
import { appConfig } from "@/appConfig";

import "react-international-phone/style.css";
import "./globals.css";

export const metadata: Metadata = {
  title:
    "Talente | Fast, confidential, and personalized support whenever you need it, helping you find better career opportunities.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" type="image/png" href="/favicon.png" />
      <body>
        {appConfig.topLoader.show && <TopLoader />}
        <CacheProvider>
          <MUIThemeProvider>
            <NotiStackProvider>
              {children}
              <Footer />
            </NotiStackProvider>
          </MUIThemeProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
